name: Pete Lada - Designer / Developer
description: I am a designer and front-end developer. I spend my time fussing with pixels in Sketch or pretending I know how to use vim. I live in the cheerful Bay Area and love coffee.
markdown: kramdown
redcarpet:
  extensions: []
highlighter: rouge
baseurl: ''
domain: petelada.com
excerpt_separator: <!--end-->
paginate: 8
paginate_path: "/posts/:num/"
gems: [jekyll-paginate]
exclude: [bower_components, node_modules, sass]


# front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      is_post: true
      type: 'post'
      read_more_text: 'Read More'
  -
    scope:
      path: ""
    values:
      show_name: true
